# Health check
GET https://localhost:86/health

### get all posts
GET https://localhost:86/api/posts

### create a new user
POST https://localhost:86/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jdoe@example.com",
  "password": "securePassword123"
}

### login as a user
POST https://localhost:86/api/auth/login
Content-Type: application/json

{
  "email": "jdoe@example.com",
  "password": "securePassword123"
}

### log out
POST https://localhost:86/api/auth/logout
// No body needed, cookies will be used to identify session