# Health check
GET https://localhost:86/health

### get all posts
GET https://localhost:86/api/posts

### create a new user
POST https://localhost:86/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jdoe@example.com"
}

### login as a user
POST https://localhost:86/api/users/login
Content-Type: application/json

{
  "email": "jdoe@example.com"
}

### get a user with id of 1
GET https://localhost:86/api/users/1